[package]
name = "circom-lsp-type-analysis"
version = "2.1.7"
authors = ["Costa Group UCM","iden3"]
edition = "2021"

[dependencies]
program_structure = {path = "../program_structure", package = "circom-lsp-program-structure", version = "2.1.7"}
num-bigint-dig = "0.8.4"
num-traits = "0.2.17"
